name: Build HappyCursor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Build project
      run: |
        xcodebuild -project HappyCursor.xcodeproj \
                   -scheme HappyCursor \
                   -configuration Release \
                   -destination 'platform=macOS' \
                   build
                   
    - name: Create app bundle
      run: |
        xcodebuild -project HappyCursor.xcodeproj \
                   -scheme HappyCursor \
                   -configuration Release \
                   -destination 'platform=macOS' \
                   archive -archivePath HappyCursor.xcarchive
                   
    - name: Export app
      run: |
        xcodebuild -exportArchive \
                   -archivePath HappyCursor.xcarchive \
                   -exportPath ./build \
                   -exportOptionsPlist exportOptions.plist
                   
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HappyCursor-app
        path: ./build/
        retention-days: 30 